# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MynervaAuthor < Formula
  desc ""
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.2/mynerva-author_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "8b2b0bcf869fdb145dba58ce47e2eb1ba3fa0a6a588fb54b32bfc74b6db9a6d0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.2/mynerva-author_0.0.2_Linux_x86_64.tar.gz"
    sha256 "9268c5cf5e32704bd92c22837e33cec2e31e3c4006935c9add2357a4c06f4580"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.2/mynerva-author_0.0.2_Linux_arm64.tar.gz"
    sha256 "092e233eab01a7afff57ab5ff76b615fd912e87b5341e93b59ca0504f8c7d7fc"
  end

  def install
    bin.install "mynerva-author"
  end
end
