# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MynervaAuthor < Formula
  desc ""
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.4/mynerva-author_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "c1fe3a30c4d031aad651a70d0406666949d5533a24cdeb178e7e96e9eee10d61"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.4/mynerva-author_0.0.4_Linux_x86_64.tar.gz"
    sha256 "2b11a52a73abe0bbf2707320f84b85c11f55a4173623e72b3bfb74a097d41c2c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.4/mynerva-author_0.0.4_Linux_arm64.tar.gz"
    sha256 "087ee5bc1b6ca582169ae6792e0d82999d28413eac85ef2979d4262ad3958616"
  end

  def install
    bin.install "mynerva-author"
  end
end
