# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MynervaAuthor < Formula
  desc ""
  homepage ""
  version "0.0.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.6/mynerva-author_0.0.6_macos_amd64.tar.gz"
    sha256 "d43a27a583861e5d2d3dec6c11c3863b4f4f05c1d85a4a98e01e118d08a27474"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.6/mynerva-author_0.0.6_linux_amd64.tar.gz"
    sha256 "3cc2750c8a9574ff100eb017f40e86a0000a2fc1b4982f3105fb4c4a26a859a1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mynerva-io/author-cli/releases/download/v0.0.6/mynerva-author_0.0.6_linux_arm64.tar.gz"
    sha256 "a8e8662905a375c5275fc22809919d11c8f7c2fa91c7def1743f41eae66b5cf2"
  end

  def install
    bin.install "mynerva-author"
  end
end
